wandb_version: 1

output_dir:
  desc: null
  value: result/RTE-facebook/opt-1.3b-KFAC-LOZO-SGD-ft-20000-16-1e-4-1e-3-0-50-16
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: None
per_gpu_eval_batch_size:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: 20000
lr_scheduler_type:
  desc: null
  value: constant
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: result/RTE-facebook/opt-1.3b-KFAC-LOZO-SGD-ft-20000-16-1e-4-1e-3-0-50-16/runs/Dec12_23-40-38_server44-ESC8000-G4
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 1
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 40000
save_total_limit:
  desc: null
  value: 1
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: None
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: None
local_rank:
  desc: null
  value: -1
xpu_backend:
  desc: null
  value: None
tpu_num_cores:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: '[]'
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 4000
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: result/RTE-facebook/opt-1.3b-KFAC-LOZO-SGD-ft-20000-16-1e-4-1e-3-0-50-16
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: None
load_best_model_at_end:
  desc: null
  value: true
metric_for_best_model:
  desc: null
  value: loss
greater_is_better:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: '[]'
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
deepspeed:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_hf
optim_args:
  desc: null
  value: None
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_bucket_cap_mb:
  desc: null
  value: None
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: None
hub_model_id:
  desc: null
  value: None
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: None
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
task_name:
  desc: null
  value: RTE
num_train:
  desc: null
  value: 1000
num_dev:
  desc: null
  value: 500
num_eval:
  desc: null
  value: 1000
num_train_sets:
  desc: null
  value: None
train_set_seed:
  desc: null
  value: 0
result_file:
  desc: null
  value: None
model_path:
  desc: null
  value: None
model_name:
  desc: null
  value: facebook/opt-1.3b
load_float16:
  desc: null
  value: false
load_bfloat16:
  desc: null
  value: true
load_int8:
  desc: null
  value: false
max_length:
  desc: null
  value: 2048
no_auto_device:
  desc: null
  value: false
sfc:
  desc: null
  value: false
icl_sfc:
  desc: null
  value: false
trainer:
  desc: null
  value: KFAC-LOZO-SGD
only_train_option:
  desc: null
  value: true
train_as_classification:
  desc: null
  value: true
zo_eps:
  desc: null
  value: 0.001
step_interval:
  desc: null
  value: 50
rank_r:
  desc: null
  value: 16
prefix_tuning:
  desc: null
  value: false
num_prefix:
  desc: null
  value: 5
no_reparam:
  desc: null
  value: true
prefix_init_by_real_act:
  desc: null
  value: true
lora:
  desc: null
  value: false
lora_alpha:
  desc: null
  value: 16
lora_r:
  desc: null
  value: 8
sampling:
  desc: null
  value: false
temperature:
  desc: null
  value: 1.0
num_beams:
  desc: null
  value: 1
top_k:
  desc: null
  value: None
top_p:
  desc: null
  value: 0.95
max_new_tokens:
  desc: null
  value: 50
eos_token:
  desc: null
  value: <EOS_TOKEN>
save_model:
  desc: null
  value: false
no_eval:
  desc: null
  value: false
tag:
  desc: null
  value: KFAC-LOZO-SGD-ft-20000-16-1e-4-1e-3-0-50-16
linear_probing:
  desc: null
  value: false
lp_early_stopping:
  desc: null
  value: false
head_tuning:
  desc: null
  value: false
untie_emb:
  desc: null
  value: false
verbose:
  desc: null
  value: false
non_diff:
  desc: null
  value: false
save_on_interrupt:
  desc: null
  value: false
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
adaptivity:
  desc: null
  value: 1.0e-08
momentum:
  desc: null
  value: 0.9
_n_gpu:
  desc: null
  value: 1
__cached__setup_devices:
  desc: null
  value: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734014440
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 7
      - 13
      - 16
      - 23
      - 66
      4: 3.10.14
      5: 0.17.6
      6: 4.28.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: float16
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - OPTForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: </s>
bos_token_id:
  desc: null
  value: 2
pad_token_id:
  desc: null
  value: 1
eos_token_id:
  desc: null
  value: 2
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: facebook/opt-1.3b
transformers_version:
  desc: null
  value: 4.28.1
activation_dropout:
  desc: null
  value: 0.0
model_type:
  desc: null
  value: opt
vocab_size:
  desc: null
  value: 50272
max_position_embeddings:
  desc: null
  value: 2048
num_attention_heads:
  desc: null
  value: 32
word_embed_proj_dim:
  desc: null
  value: 2048
ffn_dim:
  desc: null
  value: 8192
hidden_size:
  desc: null
  value: 2048
num_hidden_layers:
  desc: null
  value: 24
dropout:
  desc: null
  value: 0.1
attention_dropout:
  desc: null
  value: 0.0
activation_function:
  desc: null
  value: relu
init_std:
  desc: null
  value: 0.02
layerdrop:
  desc: null
  value: 0.0
use_cache:
  desc: null
  value: true
do_layer_norm_before:
  desc: null
  value: true
enable_bias:
  desc: null
  value: true
layer_norm_elementwise_affine:
  desc: null
  value: true
_remove_final_layer_norm:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 16
eval_batch_size:
  desc: null
  value: 8
